version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
          - CHOKIDAR_USEPOLLING=true
        ports:
            - 5000:3000
        volumes:
            - /usr/node_app/node_modules
            - /proj/section06:/usr/node_app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/node_app/node_modules
            - /proj/section06:/usr/node_app
        command: ["npm", "run", "test"]

